name: Deploy Vite-React App to GitHub Pages

on:
  # Run workflow on any push to the main branch
  push:
    branches:
      - main

  # Allows you to manually trigger the workflow from GitHub Actions tab
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # You can specify your version here

      # Install dependencies and build the project
      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      # Deploy the dist folder to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
